version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comelec2k26_app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "80:80"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY}
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
    networks:
      - comelec_network

networks:
  comelec_network:
    driver: bridge
