<?php

namespace App\Helpers;

use FPDF;
use Carbon\Carbon;

class CustomPDF extends FPDF
{
    function Header()
    {
        // Full width header image
        $pageWidth = $this->GetPageWidth();
        $this->Image(public_path('assets/header.png'), 0, 0, $pageWidth); // x=0, y=0 for top-left, width=page width
        
        // Add more space after header
        $this->Ln(30);
    }

    function Footer()
    {
        if ($this->PageNo() <= $this->getNumPages()) {
            $timestamp = Carbon::now('Asia/Manila')->format('F j, Y H:i:s T');
            
            $this->SetY(-15);
            $this->SetFont('Arial', 'I', 8);
            $this->Cell(0, 10, 'Generated by BukSU Comelec Voting System on ' . $timestamp . ' | Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
        }
    }

    function AddSignatories()
    {
        $this->Ln(20);  // Add some space
        $this->SetFont('Arial', 'B', 10);
        $this->Cell(0, 6, 'Head Commissioner:', 0, 1, 'L');
        $this->SetFont('Arial', '', 10);
        $this->Cell(40, 6, '', 0, 0, 'L'); // Add 40mm spacing from left
        $this->Cell(0, 6, 'Roxanne Ortega', 0, 1, 'L');
        $this->Ln(10);  // Add 5mm spacing
        $this->SetFont('Arial', 'B', 10);
        $this->Cell(0, 6, 'Comelec Adviser:', 0, 1, 'L');
        $this->SetFont('Arial', '', 10);
        $this->Cell(40, 6, '', 0, 0, 'L'); // Add 40mm spacing from left
        $this->Cell(0, 6, 'Mark Ian M. Mukara', 0, 1, 'L');
        $this->Ln(10);  // Add 5mm spacing
        $this->SetFont('Arial', 'B', 10);
        $this->Cell(0, 6, 'Database Administrator:', 0, 1, 'L');
        $this->SetFont('Arial', '', 10);
        $this->Cell(40, 6, '', 0, 0, 'L'); // Add 40mm spacing from left
        $this->Cell(0, 6, 'Klevie Jun Caseres', 0, 1, 'L');
        $this->Ln(10);  // Add 5mm spacing
        $this->SetFont('Arial', 'B', 10);
        $this->Cell(0, 6, 'System Administrator:', 0, 1, 'L');
        $this->SetFont('Arial', '', 10);
        $this->Cell(40, 6, '', 0, 0, 'L'); // Add 40mm spacing from left
        $this->Cell(0, 6, 'Rey Rameses Jude III S. Macalutas', 0, 1, 'L');
        $this->Ln(10);  // Add 5mm spacing
        $this->Cell(40, 6, '', 0, 0, 'L'); // Add 40mm spacing from left
        $this->Cell(0, 6, 'Khyle Ivan Khim V. Amacna', 0, 1, 'L');
        $this->Ln(10);  // Add 5mm spacing
        $this->Cell(40, 6, '', 0, 0, 'L'); // Add 40mm spacing from left
        $this->Cell(0, 6, 'Bernardo C. DeLa Cerna', 0, 1, 'L');
    }

    private function getNumPages()
    {
        return count($this->pages);
    }
}